{
  "headers": {
    "client_id": "012fdb6c04534e158f36ffb0a8071fee",
    "client_secret": "F53129583E1243fAa4fed5c0A7B23395",
    "content-type": "application/json",
    "user-agent": "PostmanRuntime/7.28.4",
    "accept": "*/*",
    "postman-token": "497bd5d6-fa7c-4dff-bac7-5bc29fd21ebb",
    "host": "localhost:8082",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive",
    "content-length": "363"
  },
  "clientCertificate": null,
  "method": "POST",
  "scheme": "http",
  "queryParams": {},
  "requestUri": "/api/bookHotel",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/bookHotel",
  "listenerPath": "/api/*",
  "relativePath": "/api/bookHotel",
  "localAddress": "/127.0.0.1:8082",
  "uriParams": {},
  "rawRequestUri": "/api/bookHotel",
  "rawRequestPath": "/api/bookHotel",
  "remoteAddress": "/127.0.0.1:50389",
  "requestPath": "/api/bookHotel"
}