#%RAML 1.0 Library

types:
  cars:
    type: object
    properties:
      carType?:
        type: string
      carNo?:
        type: string
      model?:
        type: string
      source?:
        type: string
      destination?:
        type: string
      price?:
        type: number
        
        