#%RAML 1.0 NamedExample

value:
    "hotelName": TAJ
    "hotelContactNo": 2344556678
    "travellerName": Karan
    "mobileNo": 7654321234
    "age": 30
    "roomType": Single
    "checkinDateTime": 2021-10-30T13:30:00
    "address": Mumbai
    "checkoutDateTime": 2021-10-30T13:30:00
    "paymentType": Cash
    "amountPayable": 3456
    "discount": 5
