#%RAML 1.0 NamedExample

value:
  -
    carType: Uber
    carNo: Uber324
    model: SUV
    source: mumbai
    destination: lonawala
    price: 4353
  -
    carType: Ola
    carNo: Ola2345
    model: Honda
    source: pune
    destination: lonawala
    price: 4563