#%RAML 1.0 NamedExample
value:
  -
    id : 1
    airlineName : Indigo
    source: Delhi
    destination : Mumbai
    departureDate : 2021-10-30T13:30:00
    price : 5955
    availableSeats : 30

  -
    id : 2
    airlineName : Indigo
    source: Lucknow
    destination : Bengaluru
    departureDate : 2021-10-30T13:30:00
    price : 7857
    availableSeats : 82

  -
    id : 3
    airlineName : Indigo
    source: Kolkata
    destination : Jaipur
    departureDate : 2021-10-30T13:30:00
    price : 8302
    availableSeats : 48