#%RAML 1.0 NamedExample

value:
  -
    hotelName: Taj
    address: Mumbai
    contactNo: 8976789876
    pincode: 410206
    city: Mumbai
    roomDetails:
    -
      roomType: Single
      price: 2344
      discount: 5
    -
      roomType: Double
      price: 3200
      discount: 10
    -
      roomType: Triple
      price: 4000
      discount: 10
  -
    hotelName: Taj
    address: Mumbai
    contactNo: 8976789876
    pincode: 410206
    city: Mumbai
    roomDetails:
    -
      roomType: Single
      price: 2344
      discount: 5
