#%RAML 1.0 NamedExample
value:
  message: Flight Booked Successfully!!!
  totalPrice: 7857
  bookingId: 123456ABC
  flightDetails:
    id: 2
    airlineName: Indigo
    source: Lucknow
    destination: Bengaluru
    departureDate: 2021-10-30T13:30:00

  passangerDetails:
    -
      passangerName: Karan
      age: 25
      mobileNo: 9899999999
      address: Maharashtra, Navi Mumbai
      seatNo: 43
    -
      passangerName: Karan
      age: 25
      mobileNo: 9899999999
      address: Maharashtra, Navi Mumbai
      seatNo: 43